trigger:
  branches:
    include:
      - main

pool:
  name: 'self-hosted'

variables:
- group: docker-creds
- name: SHORT_SHA
  value: $(echo $(Build.SourceVersion) | cut -c1-8)
- name: DOCKER_BUILDKIT
  value: 0

stages:
- stage: BuildApp
  displayName: 'Build App'
  jobs:
  - job: BuildApp
    displayName: 'Build App'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core'
      inputs:
        version: '9.x'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
      displayName: 'dotnet restore dependency'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration Release'
      displayName: 'dotnet build Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        arguments: '--no-restore --verbosity normal'
      displayName: 'dotnet test'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        arguments: '--configuration Release -r win-x64 -o ./publish-windows'
      displayName: 'dotnet publish Release'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/publish-windows
        artifactName: WebApp-MvcMovie-Windows-x64
- stage: BuildDocker
  displayName: Build and push docker image
  jobs:
  - job: BuildDocker
    displayName: Build Docker
    steps:
    - script: |
        curl -fSL "https://github.com/genuinetools/img/releases/download/v0.5.11/img-linux-amd64" -o "/usr/local/bin/img" \
        && chmod a+x "/usr/local/bin/img"
        img -h
      displayName: 'Install Img Binary'
    - script: |
        img login index.docker.io -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        img build -t trihatmaja/mvcmovie:$(SHORT_SHA) .
        img push trihatmaja/mvcmovie:$(SHORT_SHA)
      displayName: 'Build and push image using Img'
      env:
        DOCKER_BUILDKIT: $(DOCKER_BUILDKIT)
    # - task: Docker@2
    #   displayName: Build and push an image to container registry
    #   inputs:
    #     containerRegistry: 'docker-hub-connection'
    #     repository: trihatmaja/mvcmovie
    #     command: 'buildAndPush'
    #     tags: |
    #       azdo-$(Build.SourceVersion)
      