trigger:
  branches:
    include:
      - main

pool:
  name: 'self-hosted'

variables:
- group: docker-creds

stages:
- stage: BuildApp
  displayName: 'Build App'
  jobs:
  - job: BuildApp
    displayName: 'Build App'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core'
      inputs:
        version: '9.x'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
      displayName: 'dotnet restore dependency'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration Release'
      displayName: 'dotnet build Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        arguments: '--no-restore --verbosity normal'
      displayName: 'dotnet test'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        arguments: '--configuration Release -r win-x64 -o ./publish-windows'
      displayName: 'dotnet publish Release'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/publish-windows
        artifactName: WebApp-MvcMovie-Windows-x64
- stage: BuildDocker
  displayName: Build and push docker image
  jobs:
  - job: BuildDocker
    displayName: Build Docker
    steps:
    - script: |
        export PODMAN_VERSION=5.5.1  # sesuaikan versi stabil terbaru
        curl -LO https://github.com/mgoltzsche/podman-static/releases/download/v$(PODMAN_VERSION)/podman-linux-amd64.tar.gz
        tar -xvf podman-linux-amd64.tar.gz
        sudo mv podman /usr/local/bin/
        podman --version
      displayName: 'Install Podman Binary'
    - script: |
        SHORT_SHA=$(echo $(Build.SourceVersion) | cut -c1-8)
        podman login index.docker.io -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
        podman build -t trihatmaja/mvcmovie:$(SHORT_SHA) .
        podman push trihatmaja/mvcmovie:$(SHORT_SHA)
      displayName: 'Build and push image using podman'
    # - task: Docker@2
    #   displayName: Build and push an image to container registry
    #   inputs:
    #     containerRegistry: 'docker-hub-connection'
    #     repository: trihatmaja/mvcmovie
    #     command: 'buildAndPush'
    #     tags: |
    #       azdo-$(Build.SourceVersion)
      