trigger:
  branches:
    include:
      - main

pool:
  name: 'self-hosted'

stages:
- stage: BuildApp
  displayName: 'Build App'
  jobs:
  - job: BuildApp
    displayName: 'Build App'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core'
      inputs:
        version: '9.x'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
      displayName: 'dotnet restore dependency'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration Release'
      displayName: 'dotnet build Release'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        arguments: '--no-restore --verbosity normal'
      displayName: 'dotnet test'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish windows'
        arguments: '--configuration Release -r win-x64 -o ./publish-windows'
      displayName: 'dotnet publish Release'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: $(System.DefaultWorkingDirectory)/publish-windows
        artifactName: WebApp-MvcMovie-Windows-x64
  - stage: BuildDocker
    displayName: Build and push docker image
    jobs:
    - job: BuildDocker
      displayName: Build Docker
      steps:
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          containerRegistry: 'docker-hub-connection'
          repository: trihatmaja/mvcmovie
          command: 'buildAndPush'
          tags: |
            azdo-$(Build.SourceVersion)
      