resources:
  - ../base

configMapGenerator:
  - name: mvcmovie-config
    behavior: replace
    envs:
      - configmap.env

secretGenerator:
  - name: mvcmovie-secrets
    behavior: replace
    envs:
      - secrets.env
    type: Opaque

patches:
  - path: deploy/poc/deployment-patch.yaml    # optional: override deployment spesifik