resources:
  - ../base

configMapGenerator:
  - name: mvcmovie-config
    envs:
      - configmap.env

secretGenerator:
  - name: mvcmovie-secrets
    envs:
      - secrets.env
    type: Opaque

patches:
  - path: deployment-patch.yaml    # optional: override deployment spesifik