resources:
  - ../base

images:
  - name: trihatmaja/mvcmovie
    newTag: ${SHORT_SHA}

configMapGenerator:
  - name: mvcmovie-config
    behavior: replace
    envs:
      - configmap.env

secretGenerator:
  - name: mvcmovie-secrets
    behavior: replace
    envs:
      - secrets.env
    type: Opaque