namespace: mvcmovie

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: mvcmovie-config
    envs:
      - configmap.env

secretGenerator:
  - name: mvcmovie-secrets
    envs:
      - secrets.env
    type: Opaque