apiVersion: v1
kind: Namespace
metadata:
  name: mvcmovie
  labels:
    name: mvcmovie
    env: poc
    pic: wicaksonotrihatmaja
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: "latest"