apiVersion: v1
kind: Service
metadata:
  name: mvcmovie
  namespace: mvcmovie
  labels:
    app: mvcmovie
    env: poc
    pic: wicaksonotrihatmaja
spec:
  type: ClusterIP
  selector:
    app: mvcmovie
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP